clone_depth: 200
version: '1.9.{build}'

branches:
  only:
    - master

environment:
  matrix:
    - QTDIR: C:\Qt\5.12\mingw73_64
      MINGW: C:\Qt\Tools\mingw730_64
      DEFAULT_PROFILE: x86_64-w64-mingw32
    - QTDIR: C:\Qt\5.12\mingw73_32
      MINGW: C:\Qt\Tools\mingw730_32
      DEFAULT_PROFILE: i686-w64-mingw32

configuration: Release

install:
  - choco install -y InnoSetup
  - choco install opencv
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

build_script:
  - dir C:\tools\ /s
  - qmake laigter.pro
  - mingw32-make

after_build:
  - windeployqt release/fastqt.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\YOUR-APP-*.exe
  - path: release
    type: zip

